export {
  MAX_WORKSPACE_FILE_DRAFT_BYTES_TOTAL,
  MAX_WORKSPACE_FILE_PATH_CHARS,
  MAX_WORKSPACE_FILE_TABS_PER_WORKSPACE,
  MAX_WORKSPACE_FILE_TABS_TOTAL,
  MAX_RUNNING_TASKS,
  defaultPackageNetworkSettings,
  gitSourceCandidates,
  npmRegistryCandidates,
  parsePackageNetworkSettings,
  type DesktopCapabilityOrigin,
  type DesktopBundledExtensionSummary,
  type DesktopBundledSkillSummary,
  type DesktopBundledSkillSuiteSummary,
  type DesktopCapabilityPackageSummary,
  type DesktopCapabilityResourceType,
  type DesktopCapabilitySnapshot,
  type DesktopIntegrationStatus,
  type DesktopRecommendedPackage,
  type DesktopToolchainStatus,
  type PackageNetworkSettings,
  type PackageNetworkSnapshot,
  type PackageSourceHealth,
  type WorkspaceEntryContextAction,
  type WorkspaceEntryRequest,
  type WorkspaceFileKind,
  type WorkspaceFilePersistedState,
  type WorkspaceFilePersistedTab,
  type WorkspaceFileStateSnapshot
} from "@pi67/domain";
