export const zhCNComposerMessages = {
  attachmentReadFailed: "无法读取附件。",
  selectedAttachmentReadFailed: "无法读取所选附件。",
  dropAttachments: "释放以添加附件",
  submissionFailed: "消息未发送。草稿和附件已保留。",
  editBlockedByDraft: "输入框已有草稿或附件，请先发送或清空后再编辑历史消息。",
  pendingAttachments: "待发送附件",
  removeAttachment: (name: string) => `移除附件：${name}`,
  inputLabel: "给 Pi 发送消息",
  streamingPlaceholder: "补充要求，/ 选择指令或技能…",
  idlePlaceholder: "描述任务，/ 选择指令或技能…",
  chooseAttachment: "选择附件",
  addAttachment: "添加附件",
  slashCatalogUnavailable: "Pi 指令目录尚未加载，请稍后重试。草稿已保留。",
  slashCatalogTruncated: "指令目录不完整，无法安全判断该 / 指令。请从候选列表选择。",
  commandUnavailableWhileRunning: "当前任务运行中，扩展指令不能排入立即纠偏或完成后执行。",
  commandAttachmentsUnsupported: "扩展指令暂不支持同时携带附件。请先执行指令，再发送附件任务。",
  commandFailed: "指令未执行。草稿已保留，请查看过程或通知中的错误。",
  streamingDelivery: "运行中消息处理方式",
  steerDetail: "发送给正在执行的 Pi，可能改变当前计划",
  steer: "立即纠偏",
  followUpDetail: "当前任务结束后再发送",
  followUp: "完成后执行",
  keyboardHint: "Enter 发送 · Shift+Enter 换行",
  sending: "发送中",
  send: "发送",
  queue: "消息队列",
  queueSummary: (steeringCount: number, followUpCount: number) => (
    `${steeringCount} 条立即纠偏 · ${followUpCount} 条完成后执行`
  ),
  collapseQueue: "收起队列内容",
  inspectQueue: "查看已排队的消息",
  clearingQueue: "正在清空",
  confirmClearQueue: "确认清空",
  clearQueue: "清空全部",
  hiddenQueueItems: (count: number) => (
    `另有 ${count} 条消息未挂载，以保持输入和滚动流畅。`
  ),
  emptyQueueItem: "（空消息）",
  queueItemTruncated: "内容已截断",
  runtimeSettings: "本次发送设置",
  modelTitle: "选择本次任务使用的 Pi 模型",
  modelLabel: "Pi 模型",
  selectModel: "选择模型",
  noAvailableModels: "没有可用模型",
  unauthenticatedModel: "（当前模型未认证）",
  configureProvider: "配置 Provider…",
  modelSwitching: (model: string) => `正在切换到 ${model}…`,
  confirmingModelSwitch: (model: string) => `正在确认 ${model} 的会话状态`,
  modelSwitched: (model: string) => `已切换到 ${model}`,
  modelSwitchFailed: (model: string, detail: string) => `切换到 ${model} 失败：${detail}`,
  modelSwitchConfirmationFailed: "无法确认模型切换",
  modelSwitchStateUnconfirmed: "Pi 返回后仍无法确认当前模型，请稍后重试。",
  thinkingTitle: "设置 Pi 的思考级别",
  thinkingLabel: "Pi 思考级别",
  thinking: {
    off: "思考：关闭",
    minimal: "思考：最低",
    low: "思考：低",
    medium: "思考：中",
    high: "思考：高",
    xhigh: "思考：很高",
    max: "思考：最高",
    fallback: (level: string) => `思考：${level}`
  }
} as const;
