export const zhCNTeamChatMessages = {
  modeSwitch: "工作模式",
  work: "工作",
  chat: "聊天",
  chatUnread: (count: number) => `聊天，${count > 99 ? "99+" : count} 条未读`,
  region: "团队聊天",
  openChat: "打开团队聊天",
  workbench: "团队聊天工作台",
  channels: "频道",
  directMessages: "私信",
  teammates: "同事",
  newChannel: "新建频道",
  joinableChannel: "可加入",
  privateChannel: "私密频道",
  you: "我",
  unknownTeammate: "已离开团队的成员",
  unread: (count: number) => `${count > 99 ? "99+" : count} 条未读`,
  mentions: (count: number) => `${count > 99 ? "99+" : count} 条提及你`,
  mentionList: "提及成员",
  mentionNoMatch: "没有匹配的频道成员",
  mentionLoading: "正在读取频道成员…",
  viewerReadOnly: "团队设置为只读成员不能发言。你仍可以阅读这里的消息。",
  channelSettings: "频道设置",
  channelSettingsTitle: (name: string) => `#${name} 设置`,
  channelRename: "保存名称",
  channelRenamed: "频道名称已更新",
  channelMembers: (count: number) => `成员 · ${count}`,
  channelMembersFailed: "无法读取频道成员。",
  channelOwner: "负责人",
  channelMakeOwner: "设为负责人",
  channelConfirmOwner: (name: string) => `确认转给 ${name}`,
  channelRemove: "移出",
  channelConfirmRemove: (name: string) => `确认移出 ${name}`,
  channelAddMember: "添加成员",
  channelAddMemberPlaceholder: "选择同事",
  channelAdd: "添加",
  channelNoOneToAdd: "团队成员都已在频道中。",
  channelLeave: "退出频道",
  channelConfirmLeave: "确认退出",
  channelOwnerMustTransfer: "负责人需要先把负责人转给其他成员，才能退出频道。",
  channelArchive: "归档频道",
  channelConfirmArchive: "确认归档",
  channelArchiveHint: "归档后频道对所有成员隐藏并变为只读；消息和任务卡都会保留，团队管理员可在网页控制台恢复。",
  channelManagerHint: "只有频道负责人或团队所有者、管理员可以改名、移出成员和归档。",
  close: "关闭",
  agents: "Agent",
  agentBadge: "Agent",
  botBadge: "Bot",
  webhooks: "集成 · Webhook",
  webhooksIntro: "外部工具（CI、监控、脚本）用 Webhook 地址以机器人身份往这个频道发纯文本消息。机器人不能读取消息。",
  webhookName: "机器人名称",
  webhookCreate: "创建 Webhook",
  webhookCreating: "正在创建…",
  webhookNone: "这个频道还没有 Webhook。",
  webhookUrlOnce: "这是 Webhook 地址，只显示这一次。像密码一样保存；泄露后请立即重置。",
  webhookCopy: "复制地址",
  webhookUrl: "Webhook 地址",
  webhookCopied: "已复制",
  webhookRotate: "重置地址",
  webhookConfirmRotate: "确认重置（旧地址立即失效）",
  webhookRemove: "删除",
  webhookConfirmRemove: "确认删除",
  webhookLastUsed: (time: string) => `最近使用 ${time}`,
  webhookNeverUsed: "从未使用",
  webhookUsage: "调用：POST 该地址，JSON 内容为 {\"text\": \"消息\"}；可选 clientKey 防止重复。每分钟 30 条、每天 1000 条。",
  manageAgents: "管理我的 Agent",
  noAgents: "还没有 Agent。新建一个，同事 @它或给它发私信时，它会在你的桌面上回复。",
  noAgentsReadOnly: "团队里还没有 Agent。",
  agentMine: "我的",
  agentOnline: "在线",
  agentOffline: "离线",
  agentDisabled: "已停用",
  agentOwnedBy: (name: string) => `由 ${name} 的桌面运行`,
  agentDisclosure: (owner: string, model: string) => `发给它的消息和最近 20 条上下文会交给 ${owner} 的桌面${model ? `，使用 ${model}` : ""} 处理；它没有任何工具，也不会写入私人记忆。`,
  agentMentionDisclosure: (names: string) => `${names} 会读取这里最近 20 条消息，由其主人的桌面和模型处理。`,
  agentOfflineHint: "主人的桌面离线；10 分钟内上线会补上回复。",
  invocationQueued: (agent: string) => `${agent} 已收到，排队中`,
  invocationWaiting: (agent: string) => `${agent} 离线，等待主人的桌面上线（10 分钟内）`,
  invocationRunning: (agent: string) => `${agent} 正在回复…`,
  invocationFailed: (agent: string, reason: string) => `${agent} 未能回复：${reason}`,
  invocationExpired: (agent: string) => `${agent} 的主人未在 10 分钟内上线，请求已过期`,
  invocationRejected: (agent: string, reason: string) => `${agent} 没有处理：${reason}`,
  invocationReasons: {
    daily_limit: "今日次数已用完",
    agent_disabled: "已停用",
    not_configured: "主人还没有在桌面上设置它",
    model_unavailable: "模型不可用或不在团队允许范围内",
    runtime_error: "运行出错",
    lease_expired: "运行超时",
    cancelled: "已取消"
  } as Record<string, string>,
  agentsTitle: "我的 Agent",
  agentsIntro: "Agent 只能对话：没有任何工具，不能读写文件、运行命令或联网。它在你的桌面上运行，费用由你的模型账户承担。",
  agentCreateTitle: "新建 Agent",
  agentName: "名称",
  agentDescription: "职责说明（同事可见）",
  agentCreate: "新建",
  agentCreating: "正在新建…",
  agentSave: "保存",
  agentDailyLimit: "每日请求上限",
  agentDisable: "停用",
  agentEnable: "启用",
  agentRemove: "删除",
  agentConfirmRemove: "确认删除",
  agentDisabledByAdmin: "已被团队管理员停用，需要管理员重新启用。",
  agentNoneOwned: "你还没有 Agent。",
  agentCreateRestricted: "团队设置为只有所有者和管理员可以新建 Agent。",
  agentHostTitle: "在这台电脑上运行",
  agentHostWorkspace: "工作区（每次回复的会话保存在这里，便于你审查）",
  agentHostProject: "团队项目",
  agentHostModel: "模型",
  agentHostModelHint: "模型需在团队模型规则允许范围内。",
  agentHostEnabled: "在本机运行",
  agentHostSave: "保存运行设置",
  agentHostStop: "不在本机运行",
  agentHostNone: "未在这台电脑上运行。同事的请求会在 10 分钟后过期。",
  agentHostActive: "正在这台电脑上运行。",
  agentHostLoading: "正在读取模型与项目…",
  agentHostFailed: "无法读取模型或团队项目。",
  agentActivity: "最近运行",
  agentActivityState: { running: "运行中", replied: "已回复", failed: "失败" } as Record<string, string>,
  noChannels: "还没有频道。新建一个频道，把同一件事的讨论放在一起。",
  noTeammates: "团队里还没有其他同事。可在 New Money 网页控制台邀请同事加入。",
  signedOutTitle: "登录 New Money 后使用聊天",
  signedOutBody: "聊天基于 New Money 团队：同一团队的同事会出现在这里。工作模式不受影响。",
  openAccount: "打开账户设置",
  unavailableEntitlement: "团队的托管服务未激活，聊天暂不可用。历史消息仍保留在服务端。",
  unavailableMember: "当前设备授权的团队已不可用。请在账户设置中重新登录。",
  unavailableRejected: "New Money 拒绝了这台设备的聊天连接（登录可能已失效，或已被移出团队）。请在账户设置中重新登录。",
  connecting: "正在连接聊天服务…",
  reconnecting: "聊天连接已中断，正在重连。期间发送的消息会在恢复后补齐。",
  live: "已连接",
  loadingDirectory: "正在读取频道与同事…",
  directoryFailed: "无法读取频道与同事。",
  retry: "重试",
  selectConversation: "选择一个频道或同事开始聊天",
  selectConversationBody: "消息保存在 New Money 团队服务中，不会写入本机私人记忆。",
  loadingMessages: "正在读取消息…",
  messagesFailed: "无法读取消息。",
  loadOlder: "加载更早的消息",
  emptyConversation: "还没有消息。发出第一条吧。",
  joinTitle: (name: string) => `你还没有加入 #${name}`,
  joinBody: "加入后可以发送消息，并收到这个频道的未读提醒。",
  join: "加入频道",
  composerLabel: (target: string) => `发送到 ${target}`,
  composerPlaceholder: (target: string) => `发消息给 ${target}`,
  send: "发送",
  sending: "发送中",
  sendFailed: "发送失败",
  retrySend: "重新发送",
  discard: "丢弃",
  charactersLeft: (count: number) => `还可输入 ${count} 字`,
  overLimit: (count: number) => `已超出 ${count} 字`,
  openDirectMessageFailed: "无法打开私信",
  peerLeft: "对方已不在团队中，无法继续发送。",
  newChannelTitle: "新建频道",
  channelName: "频道名称",
  channelNameHint: "1–80 个字符，团队内不能重名。",
  visibility: "可见范围",
  publicChannel: "公开",
  publicChannelHint: "团队成员都能看到并加入",
  privateChannelHint: "只有被添加的同事能看到",
  addTeammates: "添加同事",
  cancel: "取消",
  create: "创建",
  creating: "正在创建…",
  workCard: "任务卡",
  workCardStatus: {
    todo: "待接手",
    in_progress: "进行中",
    in_review: "待验收",
    done: "已完成",
    closed: "已关闭"
  } as Record<string, string>,
  workCardAction: {
    claim: "接手",
    submit_for_review: "提交验收",
    accept: "验收通过",
    request_changes: "退回修改",
    close: "关闭",
    reopen: "重新打开"
  } as Record<string, string>,
  workCardAssignee: (name: string) => `指派给 ${name}`,
  workCardClaimedBy: (name: string) => `${name} 负责`,
  workCardUnassigned: "团队成员均可接手",
  workCardGoal: "目标",
  workCardAcceptance: "验收条件",
  workCardSummary: "交接摘要",
  workCardRefs: "参考",
  workCardActionFailed: "任务卡操作没有完成",
  startWork: "在工作中开始",
  handleInWork: "在工作中处理",
  handoffMenu: "交给同事…",
  handoffTitle: "交给同事或频道",
  handoffTarget: "发送到",
  handoffTitleField: "标题",
  handoffGoal: "目标",
  handoffAcceptance: "验收条件",
  handoffSummary: "交接摘要",
  handoffSummaryPlaceholder: "写下进展、关键发现和下一步。",
  handoffPrivacy: "只会发送你在这里填写的内容和勾选的参考；不会上传对话记录、提示词、代码或私人记忆。",
  handoffIncludeWorkspace: (name: string) => `工作区：${name}`,
  handoffIncludeBranch: (branch: string) => `分支：${branch}`,
  handoffLink: "PR 或链接（可选，仅 https）",
  handoffLinkInvalid: "请填写 https 开头的完整链接。",
  handoffSend: "发送任务卡",
  handoffSending: "正在发送…",
  handoffSent: (target: string) => `任务卡已发送到 ${target}`,
  handoffNoTargets: "还没有可发送的频道或同事。",
  handoffSignedOut: "登录 New Money 后才能把任务交给同事。",
  startWorkTitle: "在工作中开始",
  startWorkWorkspace: "工作区",
  startWorkProject: "团队项目",
  startWorkProjectHint: "团队内容只会进入团队项目范围的对话，不会写入私人记忆；发送前可以修改。",
  startWorkNoProject: "团队还没有可用项目。请在 New Money 网页控制台创建项目后再试。",
  startWorkNoWorkspace: "还没有可用的工作区。先在工作模式中添加一个工作区。",
  startWorkLoadingProjects: "正在读取团队项目…",
  startWorkProjectsFailed: "无法读取团队项目。",
  startWorkText: "起始内容",
  startWorkConfirm: "创建草稿",
  startWorkBusy: "当前有对话正在创建，请稍后再试。",
  errors: {
    work_card_revision_conflict: "任务卡刚被别人更新，已刷新为最新状态。",
    work_card_invalid_transition: "任务卡状态已变化，这个操作不再可用。",
    work_card_not_permitted: "只有被指派人或任务卡发起人可以这样操作。",
    work_card_not_found: "这张任务卡已不存在。",
    work_card_invalid: "任务卡内容超出长度限制或参考链接无效。",
    work_card_assignee_invalid: "被指派的同事不在这个会话中。",
    entitlement_inactive: "团队的托管服务未激活。",
    team_not_found: "当前团队已不可用。",
    device_team_scope: "这台设备授权的是另一个团队。",
    chat_conversation_not_found: "这个会话已不存在或你没有权限。",
    chat_membership_required: "加入频道后才能发送消息。",
    chat_channel_private: "这是私密频道，请让频道成员添加你。",
    chat_channel_name_taken: "团队里已有同名频道。",
    chat_channel_name_invalid: "频道名称需要 1–80 个可见字符。",
    chat_dm_peer_unavailable: "对方已不在团队中。",
    chat_dm_self: "不能给自己发私信。",
    chat_member_not_in_team: "所选同事已不在团队中。",
    chat_client_key_reused: "这条消息与已发送的内容冲突，请重新输入。",
    chat_body_invalid: "消息需要 1–4000 个字符。",
    chat_channel_creation_restricted: "团队设置为只有所有者和管理员可以新建频道。",
    chat_viewer_read_only: "团队设置为只读成员不能发言。",
    chat_conversation_archived: "这个频道已归档，不能再发送消息。",
    chat_mention_invalid: "只能提及这个会话里的成员。",
    chat_channel_manager_required: "只有频道负责人或团队所有者、管理员可以这样做。",
    chat_owner_must_transfer: "请先把负责人转给其他成员。",
    chat_owner_not_member: "新负责人必须已经是频道成员。",
    chat_member_not_found: "该成员已不在频道中。",
    chat_agent_creation_restricted: "你的角色不能在这个团队新建 Agent。",
    chat_agent_name_taken: "团队里已有同名 Agent。",
    chat_agent_quota_reached: "每人最多 5 个 Agent，团队最多 50 个。",
    chat_agent_invalid: "Agent 名称需要 1–40 个字符，说明不超过 280 个字符。",
    chat_agent_not_found: "这个 Agent 已不存在。",
    chat_agent_owner_required: "只有 Agent 的主人可以修改它。",
    chat_agent_manager_required: "只有 Agent 的主人或团队所有者、管理员可以这样做。",
    chat_agent_disabled_by_admin: "这个 Agent 由团队管理员停用，需要管理员重新启用。",
    chat_webhook_invalid: "机器人名称需要 1–40 个字符。",
    chat_webhook_name_taken: "这个频道已有同名的 Webhook。",
    chat_webhook_quota_reached: "每个频道最多 10 个 Webhook，团队最多 100 个。",
    chat_webhook_not_found: "这个 Webhook 已不存在。"
  } as Record<string, string>,
  genericError: "操作没有完成，请稍后重试。"
} as const;
