export const zhCNCommandPaletteMessages = {
  title: "命令面板",
  searchLabel: "搜索会话、对话正文、扩展命令和应用操作",
  searchPlaceholder: "搜索会话、对话正文、扩展命令或应用操作…",
  results: "命令面板结果",
  current: "当前",
  sessionCatalogUnavailable: "会话目录暂时不可用",
  noMatches: "没有匹配结果",
  sessionCatalogRecovery: "应用操作仍可使用；稍后重试会话搜索。",
  searchSuggestion: "尝试会话名称、对话正文、`/command` 或设置名称。",
  keyboardHelp: "选择",
  keyboardOpen: "打开",
  keyboardClose: "关闭",
  extensionLoadFailedWithFallback: "扩展命令加载失败，会话和应用操作仍可使用。",
  searchingSessions: "正在搜索会话目录…",
  loadingExtensions: "正在加载扩展命令…",
  hostUnavailable: "Pi 运行服务尚未连接，应用设置仍可使用。",
  searchScope: (sessionCount: number, extensionCount: number) => (
    `搜索范围：前 ${sessionCount} 个会话、前 ${extensionCount} 个扩展命令。`
  ),
  topResults: (count: number) => `仅显示相关度最高的 ${count} 项。`,
  searchForMore: "输入关键词可搜索更多结果。",
  currentSources: "结果仅来自本地 Pi 会话正文、Pi 命令和应用设置。",
  groupRecent: "最近使用",
  groupSessions: "会话",
  groupMessages: "对话正文",
  groupExtensions: "扩展命令",
  groupActions: "应用操作",
  groupSettings: "设置与维护",
  currentSession: "当前会话",
  currentSessionDetail: (count: number) => `当前会话 · ${count} 条消息`,
  sessionDetail: (count: number, relativeTime: string) => `${count} 条消息 · ${relativeTime}`,
  reloadResources: "重新加载 Pi 资源",
  reloadResourcesDetail: "技能、指令模板、扩展和上下文文件",
  compactSession: "压缩当前会话",
  compactSessionDetail: "使用 Pi compaction 释放上下文空间",
  credentials: "模型服务与凭据",
  credentialsDetail: "查看认证状态，配置本次运行密钥",
  updates: "检查更新",
  updatesDetail: "查看 Unsigned Preview 更新状态",
  diagnostics: "导出脱敏诊断",
  diagnosticsDetail: "不包含凭据、提示内容和源码正文",
  hostNotConnected: "Pi 运行服务尚未连接",
  sessionTransitionPending: "会话正在切换或恢复",
  sessionNotReady: "Pi 会话身份尚未就绪",
  operationActive: "当前任务结束后可用",
  extensionFallbackDescription: "Pi 扩展命令",
  sessionSearchFallback: "会话目录查询失败，正在显示最近会话中的本地匹配。",
  invalidExtensionCommands: "扩展命令返回了无效或重复的命令标识。",
  extensionCommandsLoadFailed: "扩展命令加载失败。"
} as const;
