export const zhCNOperationMessages = {
  failed: "任务失败",
  lost: "任务已中断",
  cancelled: "任务已停止",
  completed: "任务已完成",
  needsApproval: "需要你的确认",
  waitingInput: "等待你的输入",
  usingTool: "正在执行工具",
  readingFiles: "正在读取文件",
  searchingProject: "正在搜索项目",
  editingFiles: "正在修改文件",
  runningCommand: "正在执行命令",
  runningTask: "正在运行任务",
  coordinatingTask: "正在协调子任务",
  processingImage: "正在处理图片",
  callingExtension: "正在调用扩展",
  callingNamedTool: (toolName: string) => `正在调用 ${toolName}`,
  calledNamedTool: (toolName: string) => `调用 ${toolName}`,
  delegatedToolRunning: "正在执行委派工具",
  delegatedToolCompleted: "委派工具已完成",
  delegatedToolFailed: "委派工具执行失败",
  compacting: "正在压缩上下文",
  responding: "正在组织回复",
  thinking: "正在分析问题",
  importingSession: "正在导入 Pi 会话",
  accepted: "正在准备",
  running: "正在继续处理",
  timelineTitle: "执行过程",
  timelineSteps: (count: number) => `${count} 个步骤`,
  timelineEarlier: (count: number) => `查看更早的 ${count} 个步骤`,
  timelineCompleted: (count: number, duration: string) => `执行过程 · ${count} 个步骤 · ${duration}`,
  autoAuthorizationReasons: {
    "configured-source": "AUTO · 已配置来源",
    "read-only": "AUTO · 只读",
    "workspace-command": "AUTO · 工作区命令",
    "workspace-write": "AUTO · Workspace 内写入"
  },
  quiet: "暂时没有新活动",
  quietDetail: "Pi 运行服务仍在响应，可以继续等待或停止任务",
  stalled: "正在确认任务状态",
  stalledDetail: "正在确认任务仍由当前 Host 执行",
  recovering: "正在恢复任务状态",
  recoveringDetail: "正在从 Pi 运行服务重新同步权威状态",
  monitorUnavailableTitle: "任务状态监控未能加载",
  monitorUnavailableDetail: "当前工作区仍可使用，但长任务心跳异常可能无法自动触发状态恢复。",
  abortFailedTitle: "无法停止当前任务",
  compactionAcknowledgementStale: "上下文压缩确认已过期",
  compactionSettled: "上下文压缩已结束",
  compactionStarting: "正在压缩上下文",
  compactionStartFailedTitle: "无法启动会话压缩",
  runtimeDisconnected: "Pi 运行服务尚未连接。",
  sessionAuthorityUnavailable: "Pi 会话身份尚未就绪。",
  commandAcknowledgementStale: (command: string) => `命令 /${command} 确认已过期`,
  commandSettled: (command: string) => `命令 /${command} 已结束`,
  commandAccepted: (command: string) => `命令 /${command} 已接收`,
  commandFailedTitle: "无法执行 Pi 命令",
  staleAcknowledgement: "Pi 运行服务或会话已在请求期间替换，旧确认已忽略。"
} as const;
