export const zhCNRuntimeMessages = {
  unknownError: "未知错误",
  session: {
    creating: "正在创建 Pi 新会话",
    createFailed: "无法创建 Pi 会话",
    confirmingCreation: "正在确认对话是否已创建",
    creationOutcomeUnknown: "对话创建结果尚未确认。请重新检查；如仍无法确认，可放弃占位后再次新建。",
    creationRecheckMatched: "已找到新建的对话",
    creationRecheckMatchedDetail: "已通过 Pi JSONL 创建标记确认对话，可从当前页面恢复；目录信息将在后台补齐。",
    creationRecheckUnavailable: "暂时无法检查创建结果",
    creationRecheckUnavailableDetail: "对话目录尚未就绪，请等待运行服务恢复后重试。",
    creationRecheckUnresolved: "仍无法确认创建结果",
    creationRecheckUnresolvedDetail: "没有找到与本次创建标识完全一致的 Pi 对话，或发现了冲突记录。为避免打开错误对话，当前占位仍会保留。",
    creationMergeConflict: "已找到新建的对话，但现有任务和当前占位都包含未发送内容。两份内容均已保留，请先处理草稿冲突。",
    creationDismissBlocked: "无法放弃此占位",
    creationDismissBlockedDetail: "该占位仍有关联草稿或附件，请先保留内容并重新检查。",
    creationDismissed: "已放弃未确认占位",
    creationDismissedDetail: "只移除了当前窗口中的占位，没有删除或改写任何 Pi 对话记录。",
    starting: "正在启动 Pi 会话",
    forking: "正在准备 Pi 会话",
    forkFailed: "无法准备 Pi 会话",
    forkRecovered: "会话状态已重新同步，可继续使用。",
    rollingBack: "正在回退 Pi 会话",
    rolledBack: "Pi 会话已回退",
    rollbackFailed: "无法回退 Pi 会话"
  },
  worktreeCreation: {
    creating: "正在创建隔离 Worktree",
    registeringWorkspace: "正在注册隔离工作区",
    creatingSession: "正在隔离工作区中创建 Pi 会话",
    failed: "无法创建隔离 Worktree",
    recoveryRequired: "隔离 Worktree 的创建结果需要恢复确认。为避免重复创建，当前草稿和创建标识已保留。",
    invalidTask: "当前新对话草稿已变化，无法继续创建隔离 Worktree。",
    environmentHeading: "运行环境",
    localLabel: "当前工作区",
    localDescription: "直接在已选择的目录中工作",
    worktreeLabel: "隔离 Worktree",
    worktreeDescription: "首次发送时创建独立目录和 pi67/* branch",
    noSideEffect: "选择环境不会修改 Git；只有首次发送才开始创建。",
    retryInspection: "重新检查",
    availability: {
      ready: "可以创建隔离 Worktree。",
      "creation-started": "创建恢复尚未完成，当前环境选择已锁定。",
      "workspace-unavailable": "当前工作区目录不可用。",
      "workspace-untrusted": "请先信任当前工作区。",
      inspecting: "正在检查 Repository。",
      "inspection-failed": "Repository 检查失败。",
      "non-git": "当前工作区不是 Git Repository。",
      "toolchain-unavailable": "内置 Git 工具不可用。",
      "repository-stale": "Repository 状态已过期。",
      "binding-unavailable": "Git 绑定待保存。",
      "worktree-unavailable": "当前 Worktree 状态不可用于隔离创建。",
      "repository-unavailable": "Repository 当前不可用于隔离创建。"
    }
  },
  workbench: {
    restoreFailedTitle: "无法恢复工作台",
    layoutNotSavedTitle: "工作台布局未保存",
    workspaceIdentityChanged: "工作区需要重新确认",
    workspaceUnavailable: "工作区当前不可用",
    sessionPendingOpen: "会话待打开",
    workspaceRestored: "工作区已恢复",
    unnamedSession: "未命名会话",
    sessionReady: "Pi 会话已就绪"
  },
  connection: {
    restoringSession: "正在恢复 Pi 会话",
    restoreSessionFailed: "无法恢复 Pi 会话",
    sessionRestored: "Pi 会话已恢复",
    runtimeConnectionInterrupted: "Pi 运行服务连接已中断",
    runtimeConnectionRecovering: "Pi 运行服务连接已中断，正在等待恢复",
    restoreConnectionFailed: "无法恢复 Pi 运行服务连接",
    restoreConnectionFailedDetail: (detail: string) => `无法恢复 Pi 运行服务连接：${detail}`,
    systemReconnect: "系统已恢复，正在重新连接 Pi 运行服务",
    systemReconnectFailed: "系统恢复后无法连接 Pi 运行服务",
    systemReconnectFailedDetail: (detail: string) => `系统恢复后无法连接 Pi 运行服务：${detail}`,
    resyncGap: "检测到状态事件缺口，正在重新同步",
    resyncGapReady: "Pi 状态已重新同步",
    resyncGapFailed: "无法重新同步 Pi 状态",
    resyncPower: "系统已恢复，正在重新同步 Pi 状态",
    resyncPowerReady: "系统恢复后 Pi 状态已重新同步",
    resyncPowerFailed: "系统恢复后无法同步 Pi 状态",
    hostExitedRecovering: (attempt: number) => `Pi 运行服务已退出，正在进行第 ${attempt} 次恢复`,
    hostExitedStopped: "Pi 运行服务连续退出，自动恢复已停止",
    hostExitedTitle: "Pi 运行服务已退出",
    hostStartupFailed: "Pi 运行服务启动失败，现有 Pi 配置未被删除或覆盖",
    hostStartupFailedTitle: "Pi 运行服务启动失败",
    hostStartupFailedDetail: "Pi-67 Desktop 已停止自动重试，并保留现有 Pi 配置。可导出脱敏诊断以定位具体启动阶段。",
    hostStartedDegradedTitle: "已保留现有 Pi 配置",
    hostStartedDegradedDetail: "核心 Pi 功能可以继续使用；部分 Pi-67 Desktop 增强因资源冲突未加载。",
    missingRuntimeReady: "Pi 运行服务未发送 authoritative runtime.ready 事件。"
  }
} as const;
