export const zhCNTeamChatMessages = {
  modeSwitch: "工作模式",
  work: "工作",
  chat: "聊天",
  chatUnread: (count: number) => `聊天，${count > 99 ? "99+" : count} 条未读`,
  region: "团队聊天",
  openChat: "打开团队聊天",
  workbench: "团队聊天工作台",
  channels: "频道",
  directMessages: "私信",
  teammates: "同事",
  newChannel: "新建频道",
  joinableChannel: "可加入",
  privateChannel: "私密频道",
  you: "我",
  unknownTeammate: "已离开团队的成员",
  unread: (count: number) => `${count > 99 ? "99+" : count} 条未读`,
  noChannels: "还没有频道。新建一个频道，把同一件事的讨论放在一起。",
  noTeammates: "团队里还没有其他同事。可在 New Money 网页控制台邀请同事加入。",
  signedOutTitle: "登录 New Money 后使用聊天",
  signedOutBody: "聊天基于 New Money 团队：同一团队的同事会出现在这里。工作模式不受影响。",
  openAccount: "打开账户设置",
  unavailableEntitlement: "团队的托管服务未激活，聊天暂不可用。历史消息仍保留在服务端。",
  unavailableMember: "当前设备授权的团队已不可用。请在账户设置中重新登录。",
  connecting: "正在连接聊天服务…",
  reconnecting: "聊天连接已中断，正在重连。期间发送的消息会在恢复后补齐。",
  live: "已连接",
  loadingDirectory: "正在读取频道与同事…",
  directoryFailed: "无法读取频道与同事。",
  retry: "重试",
  selectConversation: "选择一个频道或同事开始聊天",
  selectConversationBody: "消息保存在 New Money 团队服务中，不会写入本机私人记忆。",
  loadingMessages: "正在读取消息…",
  messagesFailed: "无法读取消息。",
  loadOlder: "加载更早的消息",
  emptyConversation: "还没有消息。发出第一条吧。",
  joinTitle: (name: string) => `你还没有加入 #${name}`,
  joinBody: "加入后可以发送消息，并收到这个频道的未读提醒。",
  join: "加入频道",
  composerLabel: (target: string) => `发送到 ${target}`,
  composerPlaceholder: (target: string) => `发消息给 ${target}`,
  send: "发送",
  sending: "发送中",
  sendFailed: "发送失败",
  retrySend: "重新发送",
  discard: "丢弃",
  charactersLeft: (count: number) => `还可输入 ${count} 字`,
  overLimit: (count: number) => `已超出 ${count} 字`,
  openDirectMessageFailed: "无法打开私信",
  peerLeft: "对方已不在团队中，无法继续发送。",
  newChannelTitle: "新建频道",
  channelName: "频道名称",
  channelNameHint: "1–80 个字符，团队内不能重名。",
  visibility: "可见范围",
  publicChannel: "公开",
  publicChannelHint: "团队成员都能看到并加入",
  privateChannelHint: "只有被添加的同事能看到",
  addTeammates: "添加同事",
  cancel: "取消",
  create: "创建",
  creating: "正在创建…",
  errors: {
    entitlement_inactive: "团队的托管服务未激活。",
    team_not_found: "当前团队已不可用。",
    device_team_scope: "这台设备授权的是另一个团队。",
    chat_conversation_not_found: "这个会话已不存在或你没有权限。",
    chat_membership_required: "加入频道后才能发送消息。",
    chat_channel_private: "这是私密频道，请让频道成员添加你。",
    chat_channel_name_taken: "团队里已有同名频道。",
    chat_channel_name_invalid: "频道名称需要 1–80 个可见字符。",
    chat_dm_peer_unavailable: "对方已不在团队中。",
    chat_dm_self: "不能给自己发私信。",
    chat_member_not_in_team: "所选同事已不在团队中。",
    chat_client_key_reused: "这条消息与已发送的内容冲突，请重新输入。",
    chat_body_invalid: "消息需要 1–4000 个字符。"
  } as Record<string, string>,
  genericError: "操作没有完成，请稍后重试。"
} as const;
