export const zhCNRepositoryEnvironmentMessages = {
  inspect: "检查 Git",
  inspectDetail: "使用内置 Git 检查当前工作区的 Repository 与 Worktree 关系",
  inspecting: "正在检查 Git",
  refreshing: "正在更新 Git",
  inspectingDetail: "正在只读检查 Repository 与 Worktree 状态",
  primary: "主工作树",
  linked: "链接工作树",
  detached: "Detached HEAD",
  branchUnknown: "分支未知",
  readyDetail: (kind: string, branch: string, count: number) => (
    `${kind}，${branch}，Repository 共 ${count} 个 Worktree。点击刷新 Git 状态。`
  ),
  nonGit: "非 Git 目录",
  nonGitDetail: "当前工作区不是 Git Repository；Pi 会话仍可正常使用。点击刷新 Git 状态。",
  toolchainUnavailable: "内置 Git 不可用",
  toolchainUnavailableDetail: "私有 Git 工具链缺失或无效；这不会阻断普通 Pi 会话。点击刷新 Git 状态。",
  workspaceMissing: "目录不可用",
  workspaceMissingDetail: "当前工作区目录缺失或尚未重新确认。",
  worktreeMissing: "隔离 Worktree 缺失",
  worktreeMissingDetail: "只能按已提交分支重建 app-owned Worktree；未提交改动与未跟踪文件无法恢复。",
  recoverWorktree: "重建已提交状态",
  recoverWorktreeDetail: "按精确 app-owned 身份重建已提交分支；不会恢复未提交改动或未跟踪文件",
  submodulesIncomplete: "Submodule 未完整",
  submodulesNetworkRequiredDetail: "本地对象不足；只有点击后才允许 Git 发起网络或使用现有认证。",
  submodulesDivergentDetail: "Submodule checkout 与记录提交不一致；为避免覆盖本地状态，不提供自动修复。",
  submodulesConflicted: "Submodule 有冲突",
  submodulesConflictedDetail: "Submodule 存在未合并状态；Pi-67 不会自动覆盖或重置。",
  initializeSubmodules: "联网补齐",
  initializeSubmodulesDetail: "明确允许 Git 为当前工作区获取并初始化缺失 Submodule；交互式认证保持关闭",
  actionPending: "处理中…",
  actionFailed: "操作未完成；当前状态已保留，请刷新后重试。",
  stale: "Git 状态待更新",
  staleDetail: "保留上次可用的 Worktree 信息，本次只读刷新未完成。点击重试。",
  catalogUnavailable: "Git 缓存不可用",
  catalogUnavailableDetail: "当前只读检查已完成，但 Worktree 缓存未能更新；下次会从 Git 重新检查。",
  stateUnavailable: "Git 绑定待保存",
  stateUnavailableDetail: "当前只读检查已完成，但 Workspace 与 Repository 的持久绑定未能保存。点击重试。",
  failed: "Git 检查失败",
  failedDetail: "无法完成只读 Repository 检查；普通 Workspace 与 Session 不受影响。点击重试。"
} as const;
