export const zhCNOperationMessages = {
  failed: "任务失败",
  lost: "任务已中断",
  cancelled: "任务已停止",
  completed: "任务已完成",
  needsApproval: "需要你的确认",
  waitingInput: "等待你的输入",
  usingTool: "正在使用工具",
  compacting: "正在压缩上下文",
  responding: "正在回复",
  thinking: "正在思考",
  importingSession: "正在导入 Pi 会话",
  accepted: "正在准备",
  running: "正在处理",
  quiet: "暂时没有新活动",
  quietDetail: "Pi 运行服务仍在响应，可以继续等待或停止任务",
  stalled: "正在确认任务状态",
  stalledDetail: "正在确认任务仍由当前 Host 执行",
  recovering: "正在恢复任务状态",
  recoveringDetail: "正在从 Pi 运行服务重新同步权威状态",
  monitorUnavailableTitle: "任务状态监控未能加载",
  monitorUnavailableDetail: "当前工作区仍可使用，但长任务心跳异常可能无法自动触发状态恢复。",
  abortFailedTitle: "无法停止当前任务",
  compactionAcknowledgementStale: "上下文压缩确认已过期",
  compactionSettled: "上下文压缩已结束",
  compactionStarting: "正在压缩上下文",
  compactionStartFailedTitle: "无法启动会话压缩",
  runtimeDisconnected: "Pi 运行服务尚未连接。",
  sessionAuthorityUnavailable: "Pi 会话身份尚未就绪。",
  commandAcknowledgementStale: (command: string) => `命令 /${command} 确认已过期`,
  commandSettled: (command: string) => `命令 /${command} 已结束`,
  commandAccepted: (command: string) => `命令 /${command} 已接收`,
  commandFailedTitle: "无法执行 Pi 命令",
  staleAcknowledgement: "Pi 运行服务或会话已在请求期间替换，旧确认已忽略。"
} as const;
